[package]
name = "b2_lexer"
description = "Lexer"
version = "0.1.0"
edition = "2021"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "lexer.rs"

[dependencies]
b2_deps = { path = "../b2_deps" }
b2_sources = { path = "../b2_sources" }
b2_token_tree = { path = "../b2_token_tree" }
