[package]
name = "b2_sources"
description = "Source files and their relationships"
version = "0.1.0"
edition = "2021"
authors = ["Brian Anderson <andersrb@gmail.com>"]

[lib]
path = "sources.rs"

[dependencies]
b2_deps = { path = "../b2_deps" }
